/**
 * \file This files defines list of redirected (NATIVE) or redefined (DCE) libc methods
 *
 * There is also a variants NATIVE_WITH_ALIAS and DCE_WITH_ALIAS macros that can be used to define
 * two symbols: name and __name pointing to the same function call.
 *
 * Macro DCE should be defined before including this macros.  If NATIVE is not defined, it is defaulted
 * to DCE.  NATIVE_WITH_ALIAS is defaulted to NATIVE, DCE_WITH_ALIAS is defaulted to DCE.
 */

#ifndef DCE
#error Macro DCE should be defined before including libc-ns3.h
#endif

#ifndef NATIVE
#define NATIVE DCE
#endif

#ifndef NATIVE_WITH_ALIAS
#define NATIVE_WITH_ALIAS NATIVE
#endif

#ifndef DCE_WITH_ALIAS
#define DCE_WITH_ALIAS DCE
#endif


// not really a libc function, but we still need to get pointer from DCE to this function
NATIVE (dce_global_variables_setup)

NATIVE (strerror)
// NATIVE (gnu_strerror_r)
// // NATIVE (xsi_strerror_r)
// // libc->xsi_strerror_r)

DCE    (atexit)
DCE    (__cxa_finalize)
DCE    (__cxa_atexit)
// NATIVE (__gxx_personality_v0)

NATIVE_WITH_ALIAS (newlocale)
NATIVE_WITH_ALIAS (uselocale)
NATIVE_WITH_ALIAS (wctype_l)

NATIVE (wctob)
NATIVE (btowc)

NATIVE (htonl)
NATIVE (htons)
NATIVE (ntohl)
NATIVE (ntohs)
DCE    (socket)
DCE    (getsockname)
DCE    (getpeername)
DCE    (bind)
DCE    (read)
DCE    (connect)
DCE    (write)
DCE    (writev)
NATIVE (memset)
NATIVE (memcpy)
NATIVE (memcmp)
NATIVE (memmove)
NATIVE (strcpy)
NATIVE (strncpy)
NATIVE (strcat)
NATIVE (strncat)
NATIVE (strcmp)
NATIVE (strncmp)
NATIVE (strlen)
NATIVE (strchr)
NATIVE (strrchr)
NATIVE (strcasecmp)
NATIVE (strncasecmp)

DCE_WITH_ALIAS (strdup)
DCE    (strndup)
DCE    (sleep)
DCE    (fopen)
DCE    (fdopen)
DCE    (freopen)
DCE    (fclose)
DCE    (fcloseall)
DCE    (fread)
DCE    (fwrite)
DCE    (fflush)
DCE    (fseek)
DCE    (ftell)
DCE    (fgetpos)
DCE    (fsetpos)
DCE    (ferror)
DCE    (feof)
DCE    (fileno)
DCE    (clearerr)
DCE    (setvbuf)
DCE    (rewind)

// stdio
DCE    (printf)
NATIVE (fprintf)
NATIVE (sprintf)
NATIVE (snprintf)
NATIVE (asprintf)
NATIVE (dprintf)

// stdarg
DCE    (vprintf)
NATIVE (vfprintf)
NATIVE (vsprintf)
NATIVE (vsnprintf)
NATIVE (vasprintf)
NATIVE (vdprintf)

NATIVE (fputc)
NATIVE (fputs)
NATIVE (fgetc)
NATIVE (fgets)
NATIVE (ungetc)

DCE    (fcntl)
DCE    (nanosleep)

DCE    (random)
DCE    (rand)
DCE    (srandom)
DCE    (srand)
DCE    (seed48)
DCE    (drand48)
DCE    (nrand48)
DCE    (lrand48)
DCE    (mrand48)
DCE    (erand48)
DCE    (jrand48)
DCE    (srand48)
DCE    (lcong48)

// NATIVE (drand48)
// NATIVE (erand48)
// NATIVE (lrand48)
// NATIVE (nrand48)
// NATIVE (mrand48)
// NATIVE (jrand48)
// NATIVE (srand48)
// NATIVE (seed48)
// NATIVE (lcong48)

DCE    (__errno_location)
// Most likely getopt and getopt_long are broken. originally there was some hack
NATIVE (getopt)
NATIVE (getopt_long)
DCE    (getpid)
DCE    (getppid)
DCE    (getuid)
DCE    (geteuid)
DCE    (setuid)
DCE    (setgid)
DCE    (seteuid)
DCE    (setegid)
DCE    (setreuid)
DCE    (setregid)
DCE    (setresuid)
DCE    (setresgid)
NATIVE (inet_aton)
NATIVE (inet_ntoa)
DCE    (inet_ntop)
NATIVE (inet_network)
NATIVE (inet_makeaddr)
NATIVE (inet_lnaof)
NATIVE (inet_netof)
NATIVE (inet_addr)
DCE    (mmap64)
DCE    (munmap)
DCE    (__xstat)
DCE    (__lxstat)
DCE    (__fxstat)
DCE    (__xstat64)
DCE    (__lxstat64)
DCE    (__fxstat64)
DCE    (dup)
DCE    (dup2)
DCE    (open)
DCE    (close)
DCE    (unlink)
DCE    (remove)
DCE    (mkdir)
DCE    (rmdir)
DCE    (setsockopt)
DCE    (getsockopt)
DCE    (select)
DCE    (listen)
DCE    (accept)
DCE    (shutdown)
DCE    (calloc)
DCE    (malloc)
DCE    (free)
DCE    (realloc)
DCE    (gettimeofday)
DCE    (time)
DCE    (isatty)
DCE    (send)
DCE    (sendto)
DCE    (sendmsg)
DCE    (recv)
DCE    (recvfrom)
DCE    (recvmsg)
DCE    (ioctl)
DCE    (sched_yield)
DCE    (poll)
NATIVE (__cmsg_nxthdr)
NATIVE (atoi)
NATIVE (atol)
NATIVE (atoll)
NATIVE (atof)
DCE    (setitimer)
DCE    (getitimer)
DCE    (exit)
DCE    (signal)
DCE    (sigaction)
NATIVE (sigemptyset)
NATIVE (sigfillset)
NATIVE (sigaddset)
NATIVE (sigdelset)
NATIVE (sigismember)
DCE    (strtol)
DCE    (strtoll)
DCE    (strtoul)
DCE    (strtoull)
DCE    (strtod)
DCE    (getcwd)
DCE    (getwd)
DCE    (get_current_dir_name)
DCE    (chdir)
DCE    (fchdir)
NATIVE (localtime)
NATIVE (strftime)
NATIVE (__ctype_b_loc)
NATIVE (gmtime_r)

DCE    (pthread_create)
DCE    (pthread_exit)
DCE    (pthread_self)
DCE    (pthread_once)
DCE    (pthread_getspecific)
DCE    (pthread_setspecific)
DCE    (pthread_key_create)
DCE    (pthread_key_delete)
DCE    (pthread_mutex_destroy)
DCE    (pthread_mutex_init)
DCE    (pthread_mutex_lock)
DCE    (pthread_mutex_unlock)
DCE    (pthread_mutex_trylock)
DCE    (pthread_mutexattr_init)
DCE    (pthread_mutexattr_destroy)
DCE    (pthread_mutexattr_settype)
DCE    (pthread_cancel)
DCE    (pthread_kill)
DCE    (pthread_join)
DCE    (pthread_detach)
DCE    (sem_init)
DCE    (sem_destroy)
DCE    (sem_post)
DCE    (sem_wait)
DCE    (sem_timedwait)
DCE    (sem_trywait)
DCE    (sem_getvalue)
DCE    (pthread_cond_destroy)
DCE    (pthread_cond_init)
DCE    (pthread_cond_broadcast)
DCE    (pthread_cond_signal)
DCE    (pthread_cond_timedwait)
DCE    (pthread_cond_wait)
DCE    (pthread_condattr_destroy)
DCE    (pthread_condattr_init)

DCE    (gethostbyname)
DCE    (gethostbyname2)
DCE    (getaddrinfo)
DCE    (freeaddrinfo)
DCE    (gai_strerror)

DCE    (getenv)
DCE    (putenv)
DCE    (setenv)
DCE    (unsetenv)
DCE    (clearenv)

NATIVE (toupper)
NATIVE (tolower)

DCE    (timerfd_create)
DCE    (timerfd_settime)
DCE    (timerfd_gettime)

DCE    (if_nametoindex)
DCE    (fork)

NATIVE (qsort)
DCE    (umask)
DCE    (abort)
//NATIVE (ctype_tolower_loc)
NATIVE (ctime)
//NATIVE (index)
//NATIVE (rindex)
NATIVE (strtok)
NATIVE (strtok_r)
DCE    (getnameinfo)
DCE    (uname)
NATIVE (sscanf)
DCE    (execv)
DCE    (execl)
DCE    (execve)
DCE    (execvp)
DCE    (execlp)
DCE    (execle)

DCE    (wait)
DCE    (waitpid)

#undef DCE
#undef NATIVE
#undef NATIVE_WITH_ALIAS
#undef DCE_WITH_ALIAS

